language: elixir
elixir:
- 1.9.1
env:
  MIX_ENV: test
branches:
  only:
    - master
otp_release:
- '21.0'
services:
- docker
install:
- mix local.rebar --force
- mix local.hex --force
- mix deps.get
before_script:
  #- travis_wait mix dialyzer --plt
- pip install --user --upgrade awscli
- export PATH=$PATH:$HOME/.local/bin
- export AWS_DEFAULT_REGION=us-west-2
- docker-compose up -d
script:
  - mix compile
    #  - MIX_ENV=dev mix dialyzer --halt-exit-status
  - mix ecto.create
  - mix ecto.migrate
  - mix fformat --check-formatted
  - mix test
  - mix coveralls.travis --pro
cache:
  directories:
  - _build
  - deps
